language: node_js

node_js:
  - 'node'
  - '7'
  - '6'
  - '4'

script:
  - npm test

after_script:
  - npm run coverage
  - npm run coverage-report

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: '6'
      script: echo 'Deploying to npm ...'
      after_script: skip
      deploy:
        provider: npm
        email: vatev.1+npm@gmail.com
        api_key:
          secure: Gp7/ZlVpT9kjJtawsn9VnxeikhSBM2QooRsHeMBErItgyy8UTE8Pyk95r9Z0PyNSvQFDCh7dbjFMjZ6VsKuQuHeybB8nAKQhnYjzXiuCW9RB3P9x9m3y9EcBLxssFMnq1hhc74CnAOWCes5I6yii8O7TDKjWPvHjDt4cSI5Syi26xtaNZsoGu0//gMIYGFKyyWwL5tLkxR7puxbzLHIku56TND+MDDsjgwbnwwwuk4Vw+rzQL8r95HeJML7kd655YURq19wpy+XOi0VwOazLBnPcS0vq9vZ2evUztyI5ev/c6ymxakyQb578my+bzahs5P69z6VGG0WN8JL5svDYKVbbOXc2GPZ59/sTBVILg6pqMuPVTIlr2bv1bp59TsfsbifETse2xk7PbAgUazoeiEQGX3PiAaT+QMfuwHKIgXJ3crvj3Nm2/F9FPadRZAFRvoySiWbSlfkayG6cjJ1V/nR29SJRtxxTfz/MVIDw9P9yXNKV7SXuerviPTQCkk5MQhrP1dLsBl2DAXMt6bsy/+9u3E4/kcw5UZaRAxhiG3H2I5Aze2sJ6HnAgv4PgnVrsk71ujzef+Mh2wpwUbzIgX3pSE9ImYzgVZ7i6z4Ey9sZB4Sm1z/j2xBhuT2tEuGSx6rjFf507lFOSEZSmPFFV5EM3gybAgXmypy17xx20Xk=
        on:
          tags: true
          repo: catdad/dev-init
