language: node_js

node_js:
  - 'node'
  - '10'
  - '8'
  - '6'
  - '4'

script:
  - npm test

after_script:
  - npm run coverage
  - npm run coverage-report

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: '6'
      script: echo 'Deploying to npm ...'
      after_script: skip
      deploy:
        provider: npm
        email: vatev.1+npm@gmail.com
        api_key:
          secure: CMuzD9mTUGWG3bZhM/KOvZmVMn8j4Uui4NtBLBDenCgPVmB5xOVRfHEt7vbCJk/RkdsY9XWRwcyUKdPz3Y8XqxrSiyY0btoQiPpMa8onrQeIDNFY9CQuSlaLSucNidZnh/GyCfQXXY2FH9E6LL285iUGRelXrZ/GREdVzcR1DENZVdNXhawk9r9Ahr5OoVWPnAxxl6ZtV5KfKu2NWybmICRyrj/6kQl6X25+J+A1k2nb08FCG0MPML+o2brsmtZgl2KUfJQuozogfVJmQ/o+ETct258juQIIPkCoMxdxIAbMBJHAIPzegbW9BSdF7P2cgjXg9f8hAJjnRonW/7h44ncBou3kkbrbTT3c6NX9ZcPEFO1MY3jUar4GwQlhH0B5FrqtUHagPuMFRobJ0VUc1DlyPpA2srAlxErb/ml+FKIuWTyCmz93ZOCUIPZa7/DrRGUl6ozkF3jtaoUB45YoGmMJOlY5tixORhx/fo7+bmyPdsHhU1mTKsxwpMVOFZtvLYHvb6FIWjgVl5LVzh6Uh+w8m3MwVHxjACoaz7Xbv8LFyA5U5OjQSAVd1cgvrl0pJtXMEhLQbveK711WwusdTIR/U5quhgdBK+C0BQZ+6cq6fDzP3BZmrzokHbxtUtwRk9GueRV67NvOSzOw4+qewTMzZ+KSjgEf/imcNykLdZQ=
        on:
          tags: true
          repo: catdad/dev-init
